"""Tareas added

Revision ID: 2e9fb11c8c3d
Revises: 9042454ca927
Create Date: 2021-06-09 15:39:19.942753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9fb11c8c3d'
down_revision = '9042454ca927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=1500), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    # ### end Alembic commands ###
