"""cambios en nombres en tablas

Revision ID: 588bc13a45a5
Revises: 8bd2af3f08c4
Create Date: 2021-06-14 16:33:56.528106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588bc13a45a5'
down_revision = '8bd2af3f08c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=120), nullable=True),
    sa.Column('apellido_materno', sa.String(length=120), nullable=True),
    sa.Column('profesor', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('matricula', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apellido_paterno'), 'users', ['apellido_paterno'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_matricula'), 'users', ['matricula'], unique=True)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_profesor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_entrega', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=1500), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('curso')
    op.drop_table('tarea')
    op.drop_index('ix_user_apellido_paterno', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_matricula', table_name='user')
    op.drop_table('user')
    op.drop_constraint(None, 'calificaciones', type_='foreignkey')
    op.drop_constraint(None, 'calificaciones', type_='foreignkey')
    op.create_foreign_key(None, 'calificaciones', 'users', ['id_alumno'], ['id'])
    op.create_foreign_key(None, 'calificaciones', 'tareas', ['id_tarea'], ['id'])
    op.drop_constraint(None, 'usuario_curso', type_='foreignkey')
    op.drop_constraint(None, 'usuario_curso', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_curso', 'cursos', ['id_curso'], ['id'])
    op.create_foreign_key(None, 'usuario_curso', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_curso', type_='foreignkey')
    op.drop_constraint(None, 'usuario_curso', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_curso', 'user', ['id_user'], ['id'])
    op.create_foreign_key(None, 'usuario_curso', 'curso', ['id_curso'], ['id'])
    op.drop_constraint(None, 'calificaciones', type_='foreignkey')
    op.drop_constraint(None, 'calificaciones', type_='foreignkey')
    op.create_foreign_key(None, 'calificaciones', 'user', ['id_alumno'], ['id'])
    op.create_foreign_key(None, 'calificaciones', 'tarea', ['id_tarea'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('apellido_paterno', sa.VARCHAR(length=120), nullable=True),
    sa.Column('apellido_materno', sa.VARCHAR(length=120), nullable=True),
    sa.Column('matricula', sa.VARCHAR(length=10), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('profesor', sa.BOOLEAN(), nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_matricula', 'user', ['matricula'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_apellido_paterno', 'user', ['apellido_paterno'], unique=False)
    op.create_table('tarea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_curso', sa.INTEGER(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=1500), nullable=True),
    sa.Column('puntaje', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=150), nullable=True),
    sa.Column('fecha_de_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_de_entrega', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('id_profesor', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_profesor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tareas')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_users_matricula'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apellido_paterno'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
