"""profesores admin added

Revision ID: 8bd2af3f08c4
Revises: 3693631cb344
Create Date: 2021-06-12 18:35:33.061525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd2af3f08c4'
down_revision = '3693631cb344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=True),
    sa.Column('id_alumno', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('profesor', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_column('user', 'profesor')
    op.drop_table('calificaciones')
    # ### end Alembic commands ###
